import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";

const Roboto_Condense = Roboto_Condensed({ subsets: ["latin"] , weight: ["400", "700"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={Roboto_Condense.className}>
        {children}
        </body>
    </html>
  );
}
